# coding: utf-8

"""
    Father Ted API

    REST API for hand-curated Father Ted Quotes  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: dave@paddez.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.series_api import SeriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSeriesApi(unittest.TestCase):
    """SeriesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.series_api.SeriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_series_get(self):
        """Test case for series_get

        List available series.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
